### ISSUE TITLE
Stacks Cards NFT project for holidays...and beyond

### ISSUE THREAD

**Issue by falkonprods** [stacksgov/Stacks-Grant-Launchpad#220]
**Background**
Sending customized e-cards is a great and simple way to let a friend or loved one know you are thinking about them around the holidays. This project aims to take this simple idea but encapsulate each e-card as an NFT that can be claimed by the recipient. This simple idea can  provide a key new entry point for more people to download the Hiro Wallet and learn about  Bitcoin-powered NFTs.  The key will be to focus on building an onboarding flow to Stacks wallet and retrieving the NFT that can be replicated and reused within the Stacks ecosystem.

**Project Overview**
StacksCards will be an NFT-based e-card system. Anyone can create, customize and send an e-card to anyone else via email. The sender can enter a message, choose a background theme, and a new NFT will be minted.

Cards will be relatively inexpensive: likely between 2 and 5 STX which will include gas to pay for retrieving the NFT into a new wallet. We will start with whatever holiday is next when this is complete.  Ideally Christmas, but also New Years, and Chinese New Years, as well as Valentine's Day and beyond.

Since these cards can be sent to anyone using an email, this concept could prompt many new STX wallets. By including gas costs for retrieving the NFT, a new user should be  able to  receive these card without having any STX  in their wallet.

After minting, the sender will be given a link (or possibly be sent via email). This link will begin an onboarding flow that will be focused on onboarding new users to the Stacks  ecosystems. It would be our aim to include simple instructions on how to set up a Hiro wallet (as well as basic info about what an NFT  is) so that anyone - Boomer grandmas and Gen Z alike - can easily get set up. Additionally, we can include information about what STX is, where to get it, what it can do, etc.

Of course regular users will be able to simply have the NFTs transferred directly to their wallet.

**Scope**
The project has a few key aspects, the most important of which will be the "onboarding to stacks" user flow. The project will include the following key features:

**For onboarding flow:**

- Card display page. This page will come from a link in the email to the recipient and will include a hash. If the hash is valid, the user will be able to save the NFT to their  wallet. 
- Flow and solid UX onboarding. When a user lands, if they don't have a wallet, we will help them through that process. We will ensure that this process is easy for anyone.

Starting design (WIP):

![image](https://user-images.githubusercontent.com/1200120/144660256-fbb54c80-d568-4bc3-9d82-13a164454969.png)
(message @falkonprods for Figma access)

**For the cards:**

- Landing page. This page will give an overview of the project, Stacks, and the Hiro Wallet. The creation process will likely also start on this page.
- Greeting card creation page. This page will introduce the project and allow the user to enter text,  choose a card, enter the recipient information (including optional wallet address), and  finally mint the NFT and send the message to the recipient. This will include Hiro Wallet signing.
- Smart contracts. There will be a few NFT contracts required: one or more SIP-9 contracts for the cards and minting, and one that will send the NFT to the recipient’s address once they claim it (to avoid them having to pay for gas in  what may be a fresh wallet).

Starting Wireframe:

![image](https://user-images.githubusercontent.com/1200120/144660361-26f677f2-1f2e-445d-a632-590e40b22f46.png)

**Budget and Milestones**
We aim to complete this project within 10-14 days, and thus are seeking a grant to support the  rapid development and smart contract creation that goes along with this.

Total Grant Request: $10,000

M1: 5 days, $3000. UX onboarding flow design. Dynamic card creation. This will include capturing the information as entered by the user, utilizing the card selected - giving these each as much dynamic graphical changes as we can so that each card is unique - and generating an image that can be added as an NFT.

M3: 7 days, $3000. Onboarding flow starting from the user receiving the NFT, carrying through until they receive the transaction to send the NFT to their wallet.

M2: 5 days, $3000 (can be done concurrently). NFT minting and smart contract creation. This milestone will be to create the SIP-9 contract(s) and mint the actual NFT, as well as creating the contract that will enable storing of some STX and allowing the user to receive the NFT into their wallet.

M4: 2 days, $1000. Final site testing and deployment. Email service integration and licensing, misc. hosting and initial marketing costs. This will enable us to create this  the right way so that emails  will not end up in spam folders, and  to ensure we can operate this through the holiday season.

**Team**
Escape Labs, Drew Falkman and DC Collier will lead the project, but we will employ the services of  a Clarity developer and designer and possibly front end engineer to ensure this is done expediently.

**Risks**
There are no major risks - this is technologically straightforward. The only risk is the short timeframe to complete the project before the holidays. That said, we can pivot to New Years if we are a few days over, Chinese  New Year if we are a few days over, or even other  card plays like postcards using CityCoins, etc. 

**Community and Supporting Materials**
Drew and DC are currently Stacks Residents, and are developing this project to get firsthand  experience managing an NFT community. DC has a history of doing generative art in Javascript and has built other NFT projects. Drew has a long history leading teams to deliver apps including MiamiVoice, but also other large projects for startups and Fortune 500s.

**Comment by will-at-stacks** [comment]
Hi Drew, 
Thank you for the proposal.  We are definitely open to funding this grant and are excited about the number of potential new wallets this project could onboard into the Stacks ecosystem.  However, we have some comments on the approach we would like you to consider and then resubmit your application.  First, we are hoping you can revise your grant application to focus on developing a streamline onboarding process that starts with an email (received with one of your NFT cards) and ends with a new user having a hiro wallet (containing the NFT). This seems like a key component to the success of your project and something we feel would be highly valuable as a generic, reusable piece of infrasture beyond any holiday season.  Within this study can you please explain how you would sponsor transactions for these freshly created wallets, since smart contracts cannot execute sponsored transactions.

Let me know what you think—happy to discuss more on a call next week. Please reach out to will@stacks.org to set up a time.

**Comment by falkonprods** [comment]
Updated proposal to support greater efforts to support stacks onboarding process.

**Comment by dcsan** [comment]
hi @will-at-stacks thanks for the feedback! that's def our intention to make this a really smooth flow for new users. We've updated the proposal above to clarify this a little. 
For onboarding new users we plan a range of different options
- provide a 'claim' link that the sender could use _any_ medium to send - their own email, twitter DM, discord...
- also send by email from the site

The Hiro wallet will prompt people to install the wallet if they try to "claim" without a wallet installed, and so we'll be using that flow, but with more information on the value of the NFT to motivate new users over the initial hurdle of installing.

We also had some other ideas like giving the sender the option to put a STX Gift inside the card for the initial sending. This might be a really good idea for Chinese New Year in february to go with the whole [red envelope (Hongbao)](https://www.forbes.com/sites/dougyoung/2015/02/26/wechat-rattles-alibaba-in-hongbao-wars/?sh=3cf33d7e2ecc) custom that is so huge on wechat/alibaba. 

Once the infra is built out we can reuse this for multiple events - CNY, Valentine's day... lots of possibilities to expand the STX ecosystem.

**Comment by falkonprods** [comment]
Update for @will-at-stacks - we are working on this, would be great to be able to execute on talent and make the holiday  season. I'm meeting with Mitchell on 12/9 to collaboriate an onboarding project he is doing with OKCoin.

Check out this sample generative holiday art:

https://user-images.githubusercontent.com/1200120/145111737-4ef9ee8b-a88f-4caa-bb24-d4b4365b6dc9.mov

**Comment by dcsan** [comment]
hey thats the webGL 3d, we also are working on some layering, adding other items
![Frame 7](https://user-images.githubusercontent.com/514002/145177312-03746f13-3b59-4b69-9aea-ecaf22f8971f.png)
![Frame 9](https://user-images.githubusercontent.com/514002/145177317-aeb80bda-e5a7-4252-8148-267dd17f59a1.png)
![Frame 10](https://user-images.githubusercontent.com/514002/145177320-6b813722-9c04-456f-8c37-6d27cb0f47e9.png)
![Frame 15](https://user-images.githubusercontent.com/514002/145177321-8295a081-cbd3-4ba0-9899-8b5471cadd80.png)

**Comment by dcsan** [comment]
as a reference i've done a lot of generative art and computer graphics before, 
for example:
https://www.artblocks.io/project/55

we were hoping to bring more of this to the stacks ecosystem and this would be a great first project to kick things off.

**Comment by will-at-stacks** [comment]
@falkonprods @dcsan this is approved!  thanks for considering the feedback and maintaining the original spirit of your project.  the artwork is looking amazing!  onward!

**Comment by falkonprods** [comment]
AWESOME. THANKS @will-at-stacks!

**Comment by falkonprods** [comment]
all set

**Comment by falkonprods** [comment]
Pleased to announce that we have completed Milestone 1 & 2. 

**M1: 5 days, $3000. UX onboarding flow design. Dynamic card creation. This will include capturing the information as entered by the user, utilizing the card selected - giving these each as much dynamic graphical changes as we can so that each card is unique - and generating an image that can be added as an NFT.**

Onboarding flow:

![image](https://user-images.githubusercontent.com/1200120/147003031-df7c98fe-75e7-4c91-a39d-21da8dd57bb1.png)

Dynamic card creation, art generation and sending:  at https://www.dcards.art/mint

![image](https://user-images.githubusercontent.com/1200120/147003296-26f1531c-fcca-445d-a1d2-9a6a806f78f2.png)

![image](https://user-images.githubusercontent.com/1200120/147003336-6140946c-9922-4797-b0d3-a05e06e1737b.png)

**M2: 5 days, $3000 (can be done concurrently). NFT minting and smart contract creation. This milestone will be to create the SIP-9 contract(s) and mint the actual NFT, as well as creating the contract that will enable storing of some STX and allowing the user to receive the NFT into their wallet.**

Mint page: https://www.dcards.art/mint

Contract: https://explorer.stacks.co/txid/SP2RJP81KF3V6NJVZEZ2SR8DD73VQJC98EJSTQWDV.dcards-v4?chain=mainnet

Contract code: https://github.com/EscapeLabs/dCards-contracts (audited and supported by Friedger)

**Comment by jhammond2012** [comment]
@falkonprods can you reach out to me on discord? 2n10se#5020

There is a sync issue between what's here vs in the dashboard.

Thanks!

**Comment by dcsan** [comment]
hi all - 

we've actually completed the final project and it's live at https://www.dCards.art

we could probably refresh it with another artwork, as that was all made for the xmas rush.

in the end we went with a token "claim" method and letting people use their own email to send that tokenID, rather than a server side email service, which would result in a complicated opt-in flow and lots of risk of spam filters.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/514002/153085934-d553fdc1-816a-460d-bfba-92507586d93d.png">

(I saw a message in email but that comment seems to have been removed now)

we could definitely use this system for another generative art project, if anyone reading this thread is interested in collaboration please leave a comment or reach out to me directly, DMs are open @dcsan  👍

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
