### ISSUE TITLE
Attracting new developers to the ecosystem by interviewing Clarity devs/Grant recipients

### ISSUE THREAD

**Issue by JakeBlockchain** [stacksgov/Stacks-Grant-Launchpad#237]
**Background**
What problems do you aim to solve? How does it serve the mission of a user owned internet?

The objective is to get more developers interested in, and building in the Stacks ecosystem by shining light on the Stacks Grant Program. 

**Project Overview**
What solution are you providing? Who will it serve?

I will have recorded conversations with 4-6 previous Stacks Grant receivers. During the conversation I’ll explore their background, if they had previous web3 experience on a different blockchain, why they made the jump to Stacks and how the Grant process was overall. 
This benefits everyone as we get more and more developers building tech around the Stacks ecosystem. 

**Scope**
What are the components or technical specs of the project? What will the final deliverable look like? How will you measure success?

Technical components include researching previous grantees, scheduling a conversation, pre-production prep to ensure a good call is had, record call and edit video. 
Final deliverables will 4-5 long form videos (15-30 minutes) along with shorter clips for targeted sharing on social media. 
All content will be recorded in a way to be evergreen. 

**Budget and Milestones**
What grant amount are you seeking? How long will the project take in hours? If more than 20, please break down the project into milestones, with a clear output (e.g., low-fi mockup, MVP with two features) and include the estimated work hours for each milestone.

Total Grant Request: $4000

M1: First 2-3 long form videos with subsequent clips.
35-45 hours. 
$2000

M2: Second batch of 2-3 long form videos with subsequent clips. 
35-45 hours. 
$2000

**Team**
Who is building this? What relevant experience do you bring to this project? Are there skills sets you are missing that you are seeking from the community? Please share links to previous work. 

Just me. 
I’ve been running a Stacks focused podcast for the past few months. Through that I’ve been using the skills needed for this including interviewing, recording, editing and finding outlets to promote the content. 
Examples:
https://www.builtonbitcoin.xyz/
More specific example of clip breakdown:
https://twitter.com/jakeblockchain/status/1462134055864975360?s=21

**Risks**
What dependencies or obstacles do you anticipate? What contingency plans do you have in place?

The issue I have to figure out is where to post these videos to engage developers that aren't currently building on or aware of Stacks. 
I plan to engage heavily in Ethereum and other blockchain dev groups and plant the seeds to sow overtime. 

**Community and Supporting Materials**
Do you have previous projects, code commits, or experiences that are relevant to this application? What community feedback or input have you received? How do you plan to share your plan to the community over time and as the final deliverable?

The podcast is the main project that is relevant.
Talking with others in the ecosystem, a few have spoken about the importance of getting more developers on the platform, and more specially getting more content out there to educate them. 

Also, If anyone knows someone that would be a good fit to interview for this topic.
Please feel free to comment below or DM me on Twitter @jakeblockchain.
I have a few prospects in mind but I'm sure there's some hidden genius out there I'm unaware of.
Thanks!

**Comment by jruffer** [comment]
This is an interesting idea.  I would suggest maybe making a community portal and to start posting these. That way you can add to the story and show success/failure results as time goes on.

**Comment by tycho1212** [comment]
I like this! Following the grants programme from February onwards has helped me understand what's happening in the Stacks ecosystem etc. Would be great to give this more visibility as I feel a lot of people who should don't really know about the programme

**Comment by JakeBlockchain** [comment]
> This is an interesting idea. I would suggest maybe making a community portal and to start posting these. That way you can add to the story and show success/failure results as time goes on. https://foundersnetwork.com/accelerator/

That’s a good idea. I’m not super website savvy but a central place to see progress overtime on grants would be cool.  This repo does a decent job.

**Comment by JakeBlockchain** [comment]
> I like this! Following the grants programme from February onwards has helped me understand what's happening in the Stacks ecosystem etc. Would be great to give this more visibility as I feel a lot of people who should don't really know about the programme

Definitely going to start doing this.
Great way to keep a pulse on the community.   👊

**Comment by will-at-stacks** [comment]
@JakeBlockchain thank you for the application.  Collectively, we think this is a great idea and we look forward to working with you on it.  This grant is approved and funds will be disbursed soon.

We're also happy to work closely with you during this process, here are some suggested action items:
- Develop an outline for each video in Notion so that you are able to better collaborate with Foundation staff and other potential contributors.  Here is a link to a suggested Notion format for this type of a project.  Happy to discuss your thoughts on this.  (please start on this ASAP and let me know when you would like to review).
- Meet with Will and Jenny to review upcoming plans for revisions to the Grant Program so videos can reinforce those changes and associated processes.
- Meet with Louise (and possibly Mitchell) and Jenny/Will to make sure your efforts are complimentary to other video production efforts happening within the Foundation at this time.
- Coordinate with Jenny to ensure content highlights the similarities and differences between Grant program and Residency / Chapters / Advocates programs.
- Aim for each complete video to have 2 to 3 'clip-worthy' highlights for amplification by the Foundation across other socials.

Please reach out with any questions or comments will@stacks.org.

**Comment by JakeBlockchain** [comment]
Awesome. Thanks Will and team!
Will reach out via email.

**Comment by JakeBlockchain** [comment]
Update on this grant.
 I've recorded two past grant recipients so far. PseudoZach from LNswap, and Orlando from StackerDAOs.
 The former has been released into the wild (https://www.builtonbitcoin.xyz/33)
 Orlando's is 90% complete and will be released next week.
 I currently have one more interview lined up, still need to find at least one more grant recipient.

**Comment by JakeBlockchain** [comment]
Updating that this grant is now complete.
I had great conversations with past grant recipients and residents covering what they worked on and their experience interacting with the Foundation as a builder. 
All the live interviews can be found at https://www.builtonbitcoin.xyz/.
(Search Pseudozach, Drew Falkman, Orlando or Will & Jenny to find them)
They've been uploaded as podcasts, YouTube videos and clips shared across all the major Web2 platforms.
Clips i've gathered for future sharing can be viewed here.
https://www.dropbox.com/sh/hcqrhet155zg8ex/AACvoWZde7UB9VheBvE19QYha?dl=0

Will be having one more follow-up conversation with Marvin and Louise about the grant process and what they are building at Ryder. This will be closer to their NFT release in the futre.
Spoke to Will and agreed we can consider this grant complete as it stands.

Also continuing to do outreach in the Polygon & Solana Discords on my own time.

Keep building,
Jake

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
